devices([
  "iPhone 12 Pro Max",
  "iPhone 12 Pro",
  "iPhone 12",
  "iPhone 8 Plus",
  "iPhone 12 mini",
  "iPhone SE"
])

languages([
  "en-US",
  "fr-FR",
  "de-DE"
])

scheme("Screenshots (iOS)")

localize_simulator(true)

dark_mode(true)

clear_previous_screenshots(true)

launch_arguments(["-setupAppForScreenshotTarget true"])
